import type { Metadata } from "next";
import "../styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "@/config/fonts";
import { QueryProvider } from "@/services/providers/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        cssLayerName: "clerk",
      }}
    >
      <QueryProvider>
        <html
          lang="pl"
          className={`${Poppins.variable}`}
          suppressHydrationWarning
        >
          <body className="antialiased bg-custom-dark-900">{children}</body>
        </html>
      </QueryProvider>
    </ClerkProvider>
  );
}
